"""
Django settings for exhibit_guide_pwa project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment variables from .env when present.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def _bool_env(name, default=False):
    """Parse a boolean environment variable from common true/false strings."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _int_env(name, default):
    """Parse an integer environment variable with a safe fallback."""
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _bool_env('DJANGO_DEBUG', _bool_env('DEBUG', False))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-only-secret-key-set-DJANGO_SECRET_KEY-in-.env'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG is False')


def _csv_env(value):
    """Split a comma-separated environment variable into a clean list."""
    return [item.strip() for item in value.split(',') if item.strip()]


def _normalize_host(value):
    """Normalize host entries so env values can include scheme/port/path safely."""
    raw = (value or '').strip()
    if not raw:
        return ''

    candidate = raw if '://' in raw else f'//{raw}'
    parsed = urlparse(candidate)
    host = (parsed.hostname or raw).strip().lower().rstrip('.')
    return host


def _build_allowed_hosts():
    """Build ALLOWED_HOSTS from env plus Render hostname conventions."""
    hosts = []

    for host in _csv_env(os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')):
        normalized = _normalize_host(host)
        if normalized:
            hosts.append(normalized)

    render_hostname = _normalize_host(os.getenv('RENDER_EXTERNAL_HOSTNAME', ''))
    if render_hostname:
        hosts.append(render_hostname)

    # Keep the known production host as an additional safe fallback.
    hosts.append('exhibitguide.onrender.com')

    # Preserve order while removing duplicates.
    seen = set()
    unique_hosts = []
    for host in hosts:
        if host not in seen:
            unique_hosts.append(host)
            seen.add(host)
    return unique_hosts


def _build_csrf_trusted_origins(allowed_hosts):
    """Build CSRF trusted origins for HTTPS deployments and custom domains."""
    configured = [origin.strip() for origin in _csv_env(os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '')) if origin.strip()]
    if configured:
        return configured

    origins = []
    for host in allowed_hosts:
        if host in {'localhost', '127.0.0.1'}:
            continue
        origins.append(f'https://{host}')
    return origins


ALLOWED_HOSTS = _build_allowed_hosts()
CSRF_TRUSTED_ORIGINS = _build_csrf_trusted_origins(ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    'exhibits.apps.ExhibitsConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exhibit_guide_pwa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'exhibit_guide_pwa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use Postgres when DATABASE_URL is set (e.g. on Render), otherwise fall back
# to local SQLite. No flags to toggle — presence of DATABASE_URL decides.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        ssl_require=_bool_env('DJANGO_DB_SSL_REQUIRE', not DEBUG),
    )
}


# Security settings: strict defaults for production, relaxed defaults for local development.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _bool_env('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = _bool_env('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _bool_env('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = _int_env('DJANGO_SECURE_HSTS_SECONDS', 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _bool_env('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = _bool_env('DJANGO_SECURE_HSTS_PRELOAD', not DEBUG)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap5'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'

EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@exhibitguide.local')
