# Generated by Django 4.2.30 on 2026-06-23 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('show', models.TextField()),
                ('artwork', models.TextField()),
                ('artist', models.TextField()),
                ('medium', models.TextField()),
                ('dimensions_height', models.IntegerField()),
                ('dimensions_width', models.IntegerField()),
                ('provenance', models.TextField()),
                ('price', models.IntegerField()),
                ('currency', models.TextField()),
                ('tldr', models.TextField()),
                ('full_text', models.TextField()),
                ('audio_url', models.URLField()),
                ('video_url', models.URLField()),
                ('image_url', models.URLField()),
                ('qr_identifier', models.IntegerField()),
                ('publish_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exhibits',
            },
        ),
    ]
