# Generated by Django 4.2.30 on 2026-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0003_rename_name_prospect_firstname_exhibit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='artwork',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='gallery_name',
            field=models.CharField(default='Hargreaves Fine Art', max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='medium',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='show_name',
            field=models.CharField(db_column='show', max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='dwell_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='firstname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='lastname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='phone',
            field=models.CharField(help_text='Phone number in international or local format', max_length=30),
        ),
    ]
