# Generated by Django 4.2.30 on 2026-07-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0005_move_prospect_to_users_state_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(blank=True, default='exhibit_images/default.jpg', null=True, upload_to='exhibit_images/'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='qr_identifier',
            field=models.PositiveIntegerField(db_index=True, help_text='Printed QR code identifier', unique=True),
        ),
    ]
