# Generated by Django 4.2.30 on 2026-07-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0006_alter_exhibit_image_alter_exhibit_qr_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='qr_identifier',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Printed QR code identifier', null=True, unique=True),
        ),
    ]
