# Generated by Django 4.2.30 on 2026-07-08 07:22

from django.db import migrations, models
import django.db.models.deletion


def _split_artist_name(full_name):
    cleaned = (full_name or '').strip()
    if not cleaned:
        return '', ''
    parts = cleaned.split(' ', 1)
    firstname = parts[0]
    lastname = parts[1] if len(parts) > 1 else ''
    return firstname, lastname


def backfill_normalized_exhibit_data(apps, schema_editor):
    Exhibit = apps.get_model('exhibits', 'Exhibit')
    Artist = apps.get_model('exhibits', 'Artist')
    Show = apps.get_model('exhibits', 'Show')
    Artwork = apps.get_model('exhibits', 'Artwork')

    for exhibit in Exhibit.objects.all().iterator():
        firstname, lastname = _split_artist_name(exhibit.artist)
        artist, _ = Artist.objects.get_or_create(
            firstname=firstname,
            lastname=lastname,
            defaults={'nationality': ''},
        )

        publish_day = exhibit.publish_date.date() if exhibit.publish_date else None
        show, _ = Show.objects.get_or_create(
            show_name=exhibit.show_name,
            defaults={
                'start_date': publish_day,
                'end_date': publish_day,
            },
        )

        artwork, _ = Artwork.objects.get_or_create(
            title=exhibit.artwork,
            artist=artist,
            medium=exhibit.medium,
            dimensions_height=exhibit.dimensions_height,
            dimensions_width=exhibit.dimensions_width,
            provenance=exhibit.provenance,
        )

        exhibit.artwork_ref_id = artwork.pk
        exhibit.show_id = show.pk
        exhibit.save(update_fields=['artwork_ref', 'show'])


def reverse_backfill_normalized_exhibit_data(apps, schema_editor):
    # Reverse data transform is intentionally omitted for state-only rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0007_alter_exhibit_qr_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('nationality', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('dimensions_height', models.PositiveSmallIntegerField(help_text='Height in centimetres (cm)')),
                ('dimensions_width', models.PositiveSmallIntegerField(help_text='Width in centimetres (cm)')),
                ('provenance', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='exhibits.artist')),
            ],
            options={
                'db_table': 'artworks',
            },
        ),
        migrations.AddField(
            model_name='exhibit',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='exhibits.show'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='artwork_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_exhibits', to='exhibits.artwork'),
        ),
        migrations.RunPython(backfill_normalized_exhibit_data, reverse_backfill_normalized_exhibit_data),
        migrations.RemoveField(
            model_name='exhibit',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='dimensions_height',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='dimensions_width',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='show_name',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='artwork',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='artwork_ref',
            new_name='artwork',
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='exhibits.artwork'),
        ),
    ]
