# Generated by Django 4.2.30 on 2026-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0009_fix_qr_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='audio_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
    ]
