# Generated by Django 4.2.30 on 2026-06-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='show',
            field=models.TextField(db_column='show'),
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='show',
            new_name='show_name',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='gallery_name',
            field=models.TextField(default='Hargreaves Fine Art'),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('dwell_time', models.IntegerField()),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='exhibits.exhibit')),
            ],
            options={
                'db_table': 'prospects',
            },
        ),
    ]
