# Generated by Django 4.2.30 on 2026-06-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0002_alter_exhibit_show_rename_show_exhibit_show_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exhibit_images/'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='lastname',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='dimensions_height',
            field=models.PositiveSmallIntegerField(help_text='Height in centimetres (cm)'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='dimensions_width',
            field=models.PositiveSmallIntegerField(help_text='Width in centimetres (cm)'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='qr_identifier',
            field=models.PositiveIntegerField(db_index=True, help_text='Printed QR code identifier'),
        ),
    ]
