# Generated by Django 4.2.30 on 2026-07-08 07:22

from django.db import migrations, models


def backfill_prospect_name(apps, schema_editor):
    Prospect = apps.get_model('users', 'Prospect')

    for prospect in Prospect.objects.all().iterator():
        full_name = f"{prospect.firstname or ''} {prospect.lastname or ''}".strip()
        if not full_name:
            full_name = prospect.email or 'Unknown Prospect'
        prospect.name = full_name
        prospect.save(update_fields=['name'])


def reverse_backfill_prospect_name(apps, schema_editor):
    # No-op reverse; legacy fields are restored by schema rollback only.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_savedcollection_galleryinquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='call_back_request',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_prospect_name, reverse_backfill_prospect_name),
        migrations.RemoveField(
            model_name='prospect',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='lastname',
        ),
    ]
